// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvxoxlwafmufkhzamvyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2eG94bHdhZm11ZmtoemFtdnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDA5MTksImV4cCI6MjA3MTM3NjkxOX0.IXmHmck5Y7nnEfMjGXC9g2bFC-ePVmPjZxocUqRkxDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});